// Package caddy generates the proxy configuration and installs Caddy as a
// service.
//
// SPEC.md §3: RASA is a disposable installer, so the proxy must outlive it.
// Caddy is installed as its own OS service rather than embedded, which is what
// makes the whole disposable model work — it renews its own certificate via
// DNS-01 indefinitely with nothing resident.
//
// # Required Caddy modules
//
// The generated file uses two modules that stock Caddy does not ship, so the
// bundled binary must be built with xcaddy including both. A stock binary
// fails at start with an unrecognised-directive error, after RASA has already
// reported success:
//
//	xcaddy build \
//	  --with github.com/caddy-dns/dynu \
//	  --with github.com/mholt/caddy-ratelimit
//
// Pin both versions. An unpinned build means the proxy changes underneath
// users between releases (SPEC.md §17).
package caddy

import (
	"fmt"
	"sort"
	"strings"
	"time"
)

// PropagationTimeout is how long Caddy waits for the DNS-01 challenge record
// to become visible before giving up.
//
// It is exported because anything that waits on issuance has to outlast it.
// RASA's own certificate wait was once the same five minutes, so a stalled
// challenge made RASA report failure at the exact moment Caddy was still
// working — observed on a real run, which failed at 4m55s and told us nothing.
const PropagationTimeout = 5 * time.Minute

// ACME endpoints. Staging is the default in development builds because Let's
// Encrypt allows only five failed validations per hostname per hour, and
// exhausting that leaves you unable to test at all (SPEC.md §19).
const (
	ACMEStaging    = "https://acme-staging-v02.api.letsencrypt.org/directory"
	ACMEProduction = "" // empty means Caddy's default, which is production
)

// Config is everything the generated Caddyfile needs.
type Config struct {
	// Hostname is the public name, without scheme or port.
	Hostname string
	// ListenPort is 443 normally, 8443 when 443 was unavailable.
	ListenPort int

	// UpstreamAddress is where Jellyfin listens, as host:port.
	UpstreamAddress string
	// BaseURL is Jellyfin's configured base path, if the user set one. The
	// proxy must match it or every request 404s.
	BaseURL string

	// DynuAPIKeyEnv names the environment variable holding the Dynu token.
	// The value never appears in the file: the credential belongs to the
	// service, supplied through its environment (SPEC.md §14).
	DynuAPIKeyEnv string

	// OwnDomain is the user's own zone, which the Dynu provider needs stated
	// explicitly. See the comment on the generated tls block.
	OwnDomain string

	// LogPath is where Caddy writes its runtime log: startup, TLS, and every
	// message about certificate issuance. Pointing it at RASA's shared
	// directory matters because Caddy otherwise logs nowhere findable under a
	// Windows service (SPEC.md §15).
	LogPath string

	// AccessLogPath, if set, receives one line per HTTP request. A separate
	// file from LogPath on purpose: request volume would bury the issuance
	// messages a failure actually needs.
	AccessLogPath string

	// ACMECA overrides the certificate authority. Empty means production.
	ACMECA string

	// Email is optional; Let's Encrypt uses it for expiry warnings.
	Email string

	// ExtraResolvers overrides the DNS servers used for challenge propagation
	// checks. Public resolvers are used by default because a router's DNS
	// often serves stale or filtered answers.
	ExtraResolvers []string
}

// DefaultResolvers are queried during DNS-01 propagation checks.
var DefaultResolvers = []string{"1.1.1.1", "9.9.9.9"}

// Validate reports whether the configuration can produce a working file.
func (c Config) Validate() error {
	var missing []string
	if strings.TrimSpace(c.Hostname) == "" {
		missing = append(missing, "hostname")
	}
	if strings.TrimSpace(c.UpstreamAddress) == "" {
		missing = append(missing, "upstream address")
	}
	if c.ListenPort <= 0 || c.ListenPort > 65535 {
		missing = append(missing, "listen port")
	}
	if strings.TrimSpace(c.DynuAPIKeyEnv) == "" {
		missing = append(missing, "credential environment variable")
	}
	if len(missing) > 0 {
		sort.Strings(missing)
		return fmt.Errorf("caddy config is missing: %s", strings.Join(missing, ", "))
	}
	return nil
}

// SiteAddress is the site block header: the hostname, plus a port when it is
// not the default.
func (c Config) SiteAddress() string {
	if c.ListenPort == 443 || c.ListenPort == 0 {
		return c.Hostname
	}
	return fmt.Sprintf("%s:%d", c.Hostname, c.ListenPort)
}

// Generate renders the Caddyfile.
func (c Config) Generate() (string, error) {
	if err := c.Validate(); err != nil {
		return "", err
	}

	resolvers := c.ExtraResolvers
	if len(resolvers) == 0 {
		resolvers = DefaultResolvers
	}

	var b strings.Builder

	b.WriteString("# Generated by RASA for Jellyfin. Do not edit by hand —\n")
	b.WriteString("# re-running RASA will overwrite this file.\n\n")

	// Global options.
	b.WriteString("{\n")
	b.WriteString("\tadmin off\n")
	// Nothing here needs port 80, and binding it is a way to fail for no
	// reason. Automatic HTTPS otherwise starts a second server on :80 to
	// serve HTTP->HTTPS redirects; RASA only ever forwards 443 or 8443 at the
	// router, so that redirect is unreachable from the internet, while the
	// local bind still collides with IIS, Apache, or anything else already
	// holding the port — and Caddy refuses to start when it cannot bind a
	// listener. Certificates are unaffected: issuance is DNS-01 (SPEC.md §4).
	b.WriteString("\tauto_https disable_redirects\n")
	if c.Email != "" {
		fmt.Fprintf(&b, "\temail %s\n", c.Email)
	}
	if c.ACMECA != "" {
		fmt.Fprintf(&b, "\tacme_ca %s\n", c.ACMECA)
	}
	if c.LogPath != "" {
		// This configures the DEFAULT logger, and it is the one that matters.
		//
		// A `log` directive inside a site block sets up HTTP access logging
		// for that site and nothing else. Every message about certificate
		// issuance — the DNS challenge, the provider's API calls, the ACME
		// errors — goes to the default logger instead. Without this block those
		// messages go nowhere at all under a Windows service, which is exactly
		// what happened on the first real run: a stalled issuance produced a
		// completely empty caddy.log and five minutes of silence.
		//
		// The most failure-prone step in the product cannot be the one with no
		// diagnostics.
		b.WriteString("\tlog {\n")
		fmt.Fprintf(&b, "\t\toutput file %s {\n", quoteIfNeeded(c.LogPath))
		b.WriteString("\t\t\troll_size 10MiB\n")
		b.WriteString("\t\t\troll_keep 5\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t\tformat json\n")
		b.WriteString("\t}\n")
	}
	b.WriteString("}\n\n")

	fmt.Fprintf(&b, "%s {\n", c.SiteAddress())

	// TLS via DNS-01. This is what removes any need for port 80 and lets the
	// listener fall back to 8443 (SPEC.md §4).
	b.WriteString("\ttls {\n")
	if c.OwnDomain != "" {
		// A Dynu DDNS hostname is its own zone apex: getroot returns the whole
		// hostname as the zone with an empty node. The provider therefore
		// cannot infer where the zone boundary is, and without own_domain it
		// looks for a parent zone the account does not own — the challenge
		// then fails with nothing obviously wrong. Verified against a live
		// account; see SPEC.md §12.
		b.WriteString("\t\tdns dynu {\n")
		fmt.Fprintf(&b, "\t\t\tapi_token  {env.%s}\n", c.DynuAPIKeyEnv)
		fmt.Fprintf(&b, "\t\t\town_domain %s\n", c.OwnDomain)
		b.WriteString("\t\t}\n")
	} else {
		fmt.Fprintf(&b, "\t\tdns dynu {env.%s}\n", c.DynuAPIKeyEnv)
	}
	fmt.Fprintf(&b, "\t\tresolvers %s\n", strings.Join(resolvers, " "))
	// Dynu propagation runs to a couple of minutes; the default gives up
	// sooner and burns a validation attempt against the five-per-hour cap.
	fmt.Fprintf(&b, "\t\tpropagation_timeout %s\n", PropagationTimeout)
	b.WriteString("\t}\n")

	b.WriteString("\n\tencode zstd gzip\n")

	// Throttle credential stuffing. RASA is what put this login form on the
	// public internet, so it owns the consequence (SPEC.md §14).
	b.WriteString("\n")
	b.WriteString("\t# Slow down password guessing against the login endpoint.\n")
	b.WriteString("\trate_limit {\n")
	b.WriteString("\t\tzone auth {\n")
	b.WriteString("\t\t\tmatch {\n")
	// Prefixed by the base path, because the matcher sees the request as it
	// arrived. A server with a base path publishes its login endpoint at
	// /jellyfin/Users/AuthenticateByName, and an unprefixed matcher would
	// silently protect nothing. (Caddy's path matcher is case-insensitive, so
	// the casing here is cosmetic.)
	fmt.Fprintf(&b, "\t\t\t\tpath %s/Users/AuthenticateByName\n", c.basePrefix())
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t\tkey    {remote_host}\n")
	b.WriteString("\t\t\tevents 10\n")
	b.WriteString("\t\t\twindow 1m\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")

	if c.AccessLogPath != "" {
		// Access logging, deliberately a different file from the runtime log
		// above: one line per request would otherwise bury the handful of
		// lines that explain a failed certificate.
		b.WriteString("\n\tlog {\n")
		fmt.Fprintf(&b, "\t\toutput file %s {\n", quoteIfNeeded(c.AccessLogPath))
		b.WriteString("\t\t\troll_size 10MiB\n")
		b.WriteString("\t\t\troll_keep 3\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t\tformat json\n")
		b.WriteString("\t}\n")
	}

	b.WriteString("\n")
	if prefix := c.basePrefix(); prefix != "" {
		// Someone who types the bare address gets sent to the base path
		// rather than a blank page. Two handle blocks rather than a bare
		// redir: handle blocks are mutually exclusive and first-match, so the
		// root case cannot accidentally swallow requests meant for the proxy.
		//
		// The `*` is load-bearing. redir takes an optional leading matcher,
		// and a destination that begins with "/" is read as one — so
		// `redir /jellyfin/ 302` quietly becomes "match /jellyfin/, redirect
		// to the literal string 302". It parses, it validates, and it never
		// fires. Found by serving the config and asking it for the page.
		fmt.Fprintf(&b, "\thandle / {\n\t\tredir * %s/ 302\n\t}\n\n", prefix)

		// handle, never handle_path.
		//
		// A Jellyfin server with a base path serves *under* that path and
		// expects to receive it: /jellyfin/System/Info/Public is the real
		// endpoint, and /System/Info/Public is a 404. handle_path implicitly
		// strips the prefix it matched, so it would forward exactly the path
		// Jellyfin does not answer — every request 404s, through a proxy that
		// started cleanly and a setup that reported success.
		fmt.Fprintf(&b, "\thandle %s/* {\n", prefix)
		writeReverseProxy(&b, c.UpstreamAddress, "\t\t")
		b.WriteString("\t}\n")
	} else {
		writeReverseProxy(&b, c.UpstreamAddress, "\t")
	}

	b.WriteString("}\n")
	return b.String(), nil
}

// basePrefix is Jellyfin's base path with no trailing slash, or empty when the
// server is at the root.
//
// Everything that has to agree with Jellyfin's base path goes through here:
// the proxy route, the rate-limit matcher, and the URL RASA verifies. They
// were separately wrong before, which is the argument for one function.
func (c Config) basePrefix() string {
	p := strings.TrimRight(strings.TrimSpace(c.BaseURL), "/")
	if p == "" {
		return ""
	}
	if !strings.HasPrefix(p, "/") {
		p = "/" + p
	}
	return p
}

func writeReverseProxy(b *strings.Builder, upstream, indent string) {
	fmt.Fprintf(b, "%sreverse_proxy %s {\n", indent, upstream)
	// Caddy's equivalent of nginx's proxy_buffering off. Required or playback
	// stalls while the proxy accumulates a buffer.
	fmt.Fprintf(b, "%s\tflush_interval -1\n", indent)
	fmt.Fprintf(b, "%s\ttransport http {\n", indent)
	// SyncPlay and live updates hold websockets open with long idle periods;
	// the default timeout drops them.
	fmt.Fprintf(b, "%s\t\tread_timeout  10m\n", indent)
	fmt.Fprintf(b, "%s\t\twrite_timeout 10m\n", indent)
	fmt.Fprintf(b, "%s\t}\n", indent)
	fmt.Fprintf(b, "%s}\n", indent)
}

// quoteIfNeeded wraps a path in quotes when it contains spaces, which Windows
// paths routinely do.
func quoteIfNeeded(s string) string {
	if strings.ContainsAny(s, " \t") {
		return `"` + s + `"`
	}
	return s
}
