package service

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
	"time"
)

// What gets written and what gets run, separated from the doing of it.
//
// Everything here is a pure function from a Definition or Timer to text or an
// argument list. That is deliberate: this package has more system side effects
// than any other in RASA and had no tests at all, because every path through
// it wrote to /etc or shelled out to sc.exe. Splitting the decisions from the
// side effects means the decisions — which are where the bugs are — can be
// checked on any machine, including the one whose OS they are not for.
//
// The bug that motivated the split: the systemd timer quietly ignored
// EnvironmentFile, so the field documented as "how the DDNS token stays out of
// a world-readable unit file" did nothing at all.

// ---------------------------------------------------------------------------
// systemd

const systemdHeader = "# Generated by RASA for Jellyfin. Do not edit by hand.\n"

// renderServiceUnit builds the .service unit for a long-running service.
func renderServiceUnit(d Definition) string {
	var b strings.Builder
	b.WriteString(systemdHeader)
	b.WriteString("[Unit]\n")
	fmt.Fprintf(&b, "Description=%s\n", firstNonEmpty(d.Description, d.DisplayName, d.Name))
	b.WriteString("After=network-online.target\n")
	b.WriteString("Wants=network-online.target\n\n")

	b.WriteString("[Service]\n")
	b.WriteString("Type=simple\n")
	fmt.Fprintf(&b, "ExecStart=%s\n", commandLine(d.Executable, d.Args))
	if d.WorkingDir != "" {
		fmt.Fprintf(&b, "WorkingDirectory=%s\n", d.WorkingDir)
	}
	writeEnvironment(&b, d.EnvironmentFile, d.Environment)
	b.WriteString("Restart=on-failure\n")
	b.WriteString("RestartSec=10\n")
	// Binding low ports without running as root.
	b.WriteString("AmbientCapabilities=CAP_NET_BIND_SERVICE\n")
	b.WriteString("NoNewPrivileges=true\n")
	b.WriteString("PrivateTmp=true\n")
	b.WriteString("ProtectSystem=full\n\n")

	b.WriteString("[Install]\n")
	b.WriteString("WantedBy=multi-user.target\n")
	return b.String()
}

// renderTimerService builds the .service unit a .timer triggers.
//
// Type=oneshot: it runs, updates, and exits — nothing is supervised.
func renderTimerService(t Timer) string {
	var b strings.Builder
	b.WriteString(systemdHeader)
	b.WriteString("[Unit]\n")
	fmt.Fprintf(&b, "Description=%s\n", firstNonEmpty(t.Description, t.Name))
	b.WriteString("After=network-online.target\n\n")
	b.WriteString("[Service]\n")
	b.WriteString("Type=oneshot\n")
	fmt.Fprintf(&b, "ExecStart=%s\n", commandLine(t.Executable, t.Args))
	writeEnvironment(&b, t.EnvironmentFile, t.Environment)
	return b.String()
}

// renderTimerUnit builds the .timer that schedules it.
func renderTimerUnit(t Timer) string {
	interval := t.Interval
	if interval < time.Minute {
		interval = time.Minute
	}
	var b strings.Builder
	b.WriteString(systemdHeader)
	b.WriteString("[Unit]\n")
	fmt.Fprintf(&b, "Description=%s\n\n", firstNonEmpty(t.Description, t.Name))
	b.WriteString("[Timer]\n")
	if t.RunAtStartup {
		// A WAN address most often changes across a reboot, so waiting a full
		// interval after boot leaves the record stale exactly when it is most
		// likely wrong.
		b.WriteString("OnBootSec=1min\n")
	}
	fmt.Fprintf(&b, "OnUnitActiveSec=%ds\n", int(interval.Seconds()))
	b.WriteString("Persistent=true\n\n")
	b.WriteString("[Install]\n")
	b.WriteString("WantedBy=timers.target\n")
	return b.String()
}

// writeEnvironment emits the credential wiring for a unit.
//
// EnvironmentFile is preferred and is why this is one function rather than two
// loops: a systemd unit file is world-readable, so a secret passed through
// Environment= is readable by every account on the machine, while a
// root-owned 0600 file referenced by the unit is not. Both are emitted when
// both are set, because it is the caller's business whether a value is a
// secret — but the file comes first, so it is the one that wins.
func writeEnvironment(b *strings.Builder, file string, env map[string]string) {
	if file != "" {
		fmt.Fprintf(b, "EnvironmentFile=%s\n", file)
	}
	// Sorted, so re-running setup produces a byte-identical unit rather than
	// a file that appears to change on every run.
	for _, k := range sortedKeys(env) {
		fmt.Fprintf(b, "Environment=%s=%s\n", k, env[k])
	}
}

// ---------------------------------------------------------------------------
// Windows

// scCreateArgs builds the `sc.exe create` argument list.
//
// sc.exe requires the whole command line as one binPath value, and its parser
// needs a space after each equals sign — the empty-looking "binPath=" followed
// by a separate value is not a mistake.
func scCreateArgs(d Definition) []string {
	return []string{"create", d.Name,
		"binPath=", commandLine(d.Executable, d.Args),
		"start=", "auto",
		"DisplayName=", d.DisplayName,
	}
}

// schtasksCreateArgs builds the recurring `schtasks /Create` argument list.
//
// Runs as SYSTEM so it works with nobody signed in, and so it can read the
// machine-scope DPAPI credential.
func schtasksCreateArgs(t Timer) []string {
	minutes := int(t.Interval / time.Minute)
	if minutes < 1 {
		minutes = 1
	}
	return []string{"/Create", "/TN", t.Name, "/TR", commandLine(t.Executable, t.Args),
		"/SC", "MINUTE", "/MO", strconv.Itoa(minutes),
		"/RU", "SYSTEM", "/RL", "HIGHEST", "/F"}
}

// schtasksBootArgs builds the separate boot trigger, because a WAN address
// most often changes across a reboot and the minute-interval trigger would
// leave the record stale until its next tick.
func schtasksBootArgs(t Timer) []string {
	return []string{"/Create", "/TN", t.Name + bootTaskSuffix, "/TR", commandLine(t.Executable, t.Args),
		"/SC", "ONSTART", "/RU", "SYSTEM", "/RL", "HIGHEST", "/F"}
}

// bootTaskSuffix names the companion task. Removal has to know it too, or an
// uninstall leaves a task behind that runs a binary it also deleted.
const bootTaskSuffix = "AtStartup"

// parseServiceStatus reads `sc.exe query` output.
//
// A non-zero exit is not necessarily a failure: 1060 is "service does not
// exist", which is an answer.
func parseServiceStatus(out string, err error) Status {
	low := strings.ToLower(out)
	if err != nil {
		if strings.Contains(out, "1060") || strings.Contains(low, "does not exist") {
			return StatusNotPresent
		}
		return StatusUnknown
	}
	switch {
	case strings.Contains(low, "running"):
		return StatusRunning
	case strings.Contains(low, "stopped"):
		return StatusStopped
	}
	return StatusUnknown
}

// quoteArg wraps a value in quotes when it contains spaces, which Windows
// paths routinely do.
func quoteArg(s string) string {
	if strings.ContainsAny(s, " \t") && !strings.HasPrefix(s, `"`) {
		return `"` + s + `"`
	}
	return s
}

// ---------------------------------------------------------------------------

// commandLine joins an executable and its arguments into one string, quoting
// each part that needs it.
//
// Shared by both platforms because both need exactly this: systemd's ExecStart
// and sc.exe's binPath are each a single value holding a whole command line,
// and an unquoted "C:\Program Files\..." breaks both in the same way.
func commandLine(exe string, args []string) string {
	out := quoteArg(exe)
	for _, a := range args {
		out += " " + quoteArg(a)
	}
	return out
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func firstNonEmpty(vals ...string) string {
	for _, v := range vals {
		if strings.TrimSpace(v) != "" {
			return v
		}
	}
	return ""
}
